### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by fransiscusrolandamalau** [rexshijaku/sql-to-ci-builder#2]
https://sql-to-ci-builder.herokuapp.com/

**Comment by rexshijaku** [comment]
Hello @fransiscusrolandamalau and thanks for the feedback! The Demo stops working at the end of each month because I hosted it on a free hosting provider and it reaches maximum "dyno hours". I will move this demo to another server and this will should not happen afterwards. Sorry for the inconvenience.

**Comment by fransiscusrolandamalau** [comment]
Thank you
